Binary Search Tree
yangshun/lago pull request #37
Opened 2017-12-25 19:15 UTC by tgrander

Binary Search Tree data structure

2017-12-25 19:30 UTC, yangshun requested changes
Thanks! This looks very good in general. Just a couple of small changes before merging 👍

2017-12-25 19:30 UTC, yangshun commented on lib/data-structures/BinarySearchTree.js
> +   * Recrusively get the minimum value in the tree.
Typo - `Recrusively`

2017-12-25 19:30 UTC, yangshun commented on lib/data-structures/BinarySearchTree.js
> +      this._root = new BinaryTreeNode(value);
Prefer early return here - can remove the `else`

2017-12-25 19:30 UTC, yangshun commented on lib/data-structures/BinarySearchTree.js
> +    if (!right) return node;
Shouldn't this return `node.getValue()`?

2017-12-25 19:30 UTC, yangshun commented on lib/data-structures/BinarySearchTree.js
> +   * @return {*} Either the value or null if value is not found
I think search should return `true`/`false` to indicate existence.

2017-12-25 19:41 UTC, tgrander commented
All comments responded to!

2017-12-25 19:55 UTC, tgrander commented
Also updated tests to reflect changes

2017-12-25 20:40 UTC, yangshun requested changes
Just some final nits, thanks a lot 😄

2017-12-25 20:40 UTC, yangshun commented on lib/data-structures/BinarySearchTree.js
> +   * @return {*} Either the value or null if value is not found
The doc's return type needs to be updated.

2017-12-25 20:40 UTC, yangshun commented on lib/data-structures/BinarySearchTree.js
> +   * @return {*}
Return `undefined`

2017-12-26 00:48 UTC, yangshun approved these changes

2017-12-26 00:48 UTC, merged

2017-12-26 00:49 UTC, yangshun commented
Many thanks! 🎉